"""Fixed type to News.published

Revision ID: e158ceaa7093
Revises: 4ffd9ba6428e
Create Date: 2024-08-31 17:06:00.080921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e158ceaa7093'
down_revision = '4ffd9ba6428e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_users')
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.alter_column('published',
               existing_type=sa.DATETIME(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.alter_column('published',
               existing_type=sa.String(),
               type_=sa.DATETIME(),
               existing_nullable=True)
    # ### end Alembic commands ###
